first commit

diff --git a/.github/workflows/on_push_in_main.yml b/.github/workflows/on_push_in_main.yml
--- a/.github/workflows/on_push_in_main.yml
+++ b/.github/workflows/on_push_in_main.yml
@@ -18,12 +18,13 @@ jobs:
           aws-region: us-east-1
 
       - name: Deploy static site to S3 bucket
+        id: deploy
         run: aws s3 sync ./public/ s3://awsdevops.click --delete
 
       - name: Collect status
         id: collect_status
         run: |
-          echo "DEPLOY_STATUS=$([[ '${{ steps.apply.outcome }}' == 'upload: public/index.html to s3://awsdevops.click/index.html' ]] && echo '✅ Success' || echo '❌ Failed')" >> $GITHUB_ENV
+          echo "DEPLOY_STATUS=$([[ '${{ steps.deploy.outcome }}' == 'success' ]] && echo '✅ Success' || echo '❌ Failed')" >> $GITHUB_ENV
 
       - name: Send Telegram Notification
         if: always()
